import type { SubscriptionTier } from "./schema";

export interface TierLimits {
  chatbots: number; // -1 means unlimited
  conversationsPerMonth: number;
  knowledgeBaseSizeMB: number;
  features: {
    embed: boolean;
    analytics: boolean;
    manualTraining: boolean;
    emailNotifications: boolean;
    leadExport: boolean;
    proactiveChat: boolean;
    autoRefresh: boolean;
    customColors: boolean;
    customLogo: boolean;
    autoGeneratedQuestions: boolean;
  };
}

export const TIER_LIMITS: Record<SubscriptionTier, TierLimits> = {
  free: {
    chatbots: 1,
    conversationsPerMonth: 3, // 3 total questions for testing
    knowledgeBaseSizeMB: 100,
    features: {
      embed: true,
      analytics: false,
      manualTraining: false,
      emailNotifications: false,
      leadExport: false,
      proactiveChat: false,
      autoRefresh: false,
      customColors: false,
      customLogo: false,
      autoGeneratedQuestions: false,
    },
  },
  starter: {
    chatbots: 1,
    conversationsPerMonth: 1000,
    knowledgeBaseSizeMB: 500, // 500 MB
    features: {
      embed: true,
      analytics: false,
      manualTraining: false,
      emailNotifications: false,
      leadExport: true, // Lead capture included in Starter
      proactiveChat: false,
      autoRefresh: false,
      customColors: true,
      customLogo: true,
      autoGeneratedQuestions: true, // Auto-generated questions included in Starter
    },
  },
  business: {
    chatbots: 3,
    conversationsPerMonth: 5000,
    knowledgeBaseSizeMB: 1024, // 1 GB
    features: {
      embed: true,
      analytics: false,
      manualTraining: true,
      emailNotifications: true,
      leadExport: true,
      proactiveChat: true,
      autoRefresh: true,
      customColors: true,
      customLogo: true,
      autoGeneratedQuestions: true,
    },
  },
  pro: {
    // Keep for backward compatibility - same as business
    chatbots: 3,
    conversationsPerMonth: 5000,
    knowledgeBaseSizeMB: 1024, // 1 GB
    features: {
      embed: true,
      analytics: false,
      manualTraining: true,
      emailNotifications: true,
      leadExport: true,
      proactiveChat: true,
      autoRefresh: true,
      customColors: true,
      customLogo: true,
      autoGeneratedQuestions: true,
    },
  },
  scale: {
    chatbots: -1, // unlimited
    conversationsPerMonth: 50000,
    knowledgeBaseSizeMB: 5120, // 5 GB
    features: {
      embed: true,
      analytics: true,
      manualTraining: true,
      emailNotifications: true,
      leadExport: true,
      proactiveChat: true,
      autoRefresh: true,
      customColors: true,
      customLogo: true,
      autoGeneratedQuestions: true,
    },
  },
};

export interface PricingPlan {
  name: string;
  tier: SubscriptionTier;
  monthlyPrice: number;
  annualPrice: number;
  description: string;
  features: string[];
  limits: TierLimits;
  popular?: boolean;
}

export const PRICING_PLANS: PricingPlan[] = [
  {
    name: "Free",
    tier: "free",
    monthlyPrice: 0,
    annualPrice: 0,
    description: "Perfect for testing",
    features: [
      "1 chatbot",
      "3 total questions",
      "100 MB knowledge base",
      "Embed on your website",
      "Share via QR code & link",
      "Basic support",
    ],
    limits: TIER_LIMITS.free,
  },
  {
    name: "Starter",
    tier: "starter",
    monthlyPrice: 24.99,
    annualPrice: 249,
    description: "For small businesses",
    features: [
      "1 chatbot",
      "1,000 conversations/month",
      "500 MB knowledge base",
      "Embed on your website",
      "Share via QR code & link",
      "Custom colors & logo",
      "Lead capture & export",
      "Auto-generated questions",
      "Email support",
    ],
    limits: TIER_LIMITS.starter,
  },
  {
    name: "Business",
    tier: "business",
    monthlyPrice: 49,
    annualPrice: 490,
    description: "For growing businesses",
    features: [
      "3 chatbots",
      "5,000 conversations/month",
      "1 GB knowledge base",
      "Everything in Starter, plus:",
      "Lead capture & export",
      "Live agent handoff",
      "Team members (up to 3)",
      "CRM integration",
      "Manual answer training",
      "Email notifications",
      "Proactive chat popup",
      "Auto knowledge refresh",
      "Priority support",
    ],
    limits: TIER_LIMITS.business,
    popular: true,
  },
  {
    name: "Scale",
    tier: "scale",
    monthlyPrice: 129,
    annualPrice: 1290,
    description: "For high-volume businesses",
    features: [
      "Unlimited chatbots",
      "50,000 conversations/month",
      "5 GB knowledge base",
      "Everything in Business, plus:",
      "Advanced analytics dashboard",
      "Unlimited team members",
      "Advanced CRM integrations",
      "Overage billing available",
      "Dedicated support",
    ],
    limits: TIER_LIMITS.scale,
  },
];

// Helper function to check if a user has access to a feature
export function hasFeatureAccess(
  tier: SubscriptionTier,
  feature: keyof TierLimits["features"]
): boolean {
  return TIER_LIMITS[tier].features[feature];
}

// Helper function to check if a user is within their chatbot limit
export function canCreateChatbot(tier: SubscriptionTier, currentCount: number): boolean {
  const limit = TIER_LIMITS[tier].chatbots;
  return limit === -1 || currentCount < limit;
}

// Helper function to check if user is within conversation limit
export function canSendMessage(tier: SubscriptionTier, currentCount: number): boolean {
  const limit = TIER_LIMITS[tier].conversationsPerMonth;
  return currentCount < limit;
}

// Helper function to check knowledge base size
export function canAddToKnowledgeBase(
  tier: SubscriptionTier,
  currentSizeMB: number,
  additionalSizeMB: number
): boolean {
  const limit = TIER_LIMITS[tier].knowledgeBaseSizeMB;
  return currentSizeMB + additionalSizeMB <= limit;
}

// Legacy constant for backwards compatibility
export const FREE_TIER_QUESTION_LIMIT = 3;
